import { createSlice } from '@reduxjs/toolkit';


export const usersSlice = createSlice({
    name: 'users',
    initialState: {
        items: {
            name: "",
            email: "",
        },
        loading: null,
        success: false,
        error: false,

    },
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        addUser: (state, action) => {
            state.name = action.payload.name;
            state.email = action.payload.email;
        },
        loadingUsers: (state, action) => {
            state.loading = true
        },
        successUsers: (state, action) => {
            state.items = action.payload;
            state.loading = null;
        },
        errorUsers: (state, action) => {
            state.error = true;
            state.loading = false;
        },

    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: () => {

    },
});

export const { addUser, loadingUsers, successUsers, errorUsers } = usersSlice.actions;

export default usersSlice.reducer;